module.exports = [
    { category: "Note", label: "Toggle Editor/Preview", cmd: "Meta-Shift-P" },
    { category: "Note", label: "Edit Note Tags", cmd: "Meta-'" },
    { category: "Note", label: "Copy Note Link", cmd: "Control-Alt-Meta-C" },
    { category: "Note", label: "Delete Note", cmd: "Meta-Delete" },
    { category: "Cell", label: "New Cell", cmd: "Shift-Enter" },
    { category: "Cell", label: "New Cell Above", cmd: "Meta-Shift-Enter" },
    { category: "Cell", label: "New Cell At Cursor", cmd: "Meta-Shift-I" },
    { category: "Cell", label: "Split Cell", cmd: "Alt-Meta-Enter" },
    { category: "Cell", label: "Cut Cell", cmd: "Meta-Shift-X" },
    { category: "Cell", label: "Copy Cell", cmd: "Meta-Shift-C" },
    { category: "Cell", label: "Paste Cell", cmd: "Meta-Shift-V" },
    { category: "Cell", label: "Delete Cell", cmd: "Meta-Shift-K" },
    { category: "Cell", label: "Convert to Text Cell", cmd: "Alt-Meta-1" },
    { category: "Cell", label: "Convert to Code Cell", cmd: "Alt-Meta-2" },
    { category: "Cell", label: "Convert to Markdown Cell", cmd: "Alt-Meta-3" },
    { category: "Cell", label: "Move Cell Up", cmd: "Alt-Meta-ArrowUp" },
    { category: "Cell", label: "Move Cell Down", cmd: "Alt-Meta-ArrowDown" },
    { category: "Format", label: "Heading 1", cmd: "Control-Shift-1" },
    { category: "Format", label: "Heading 2", cmd: "Control-Shift-2" },
    { category: "Format", label: "Heading 3", cmd: "Control-Shift-3" },
    { category: "Format", label: "Heading 4", cmd: "Control-Shift-4" },
    { category: "Format", label: "Increase Heading Level", cmd: "Control-Shift-]" },
    { category: "Format", label: "Decrease Deading Level", cmd: "Control-Shift-[" },
    { category: "Format", label: "Add/Edit Link", cmd: "Meta-K" },
    { category: "Format", label: "Bold", cmd: "Meta-B" },
    { category: "Format", label: "Italic", cmd: "Meta-I" },
    { category: "Format", label: "Underline", cmd: "Meta-U" },
    { category: "Format", label: "Strikethrough", cmd: "Control-Shift-S" },
    { category: "Format", label: "Highlight", cmd: "Control-Shift-H" },
    { category: "Format", label: "Inline Code", cmd: "Control-Shift-K" },
];
