module.exports = [
    { id: "gggMznAS6fKWLggtmP9joM", app: 'quiver', category: "Note", label: "Toggle Editor/Preview", command: "Meta-Shift-P" },
    { id: "rDycmJYyEUbUL1pDGCWs36", app: 'quiver', category: "Note", label: "Edit Note Tags", command: "Meta-'" },
    { id: "kiy8QHguZk4GUy5yY2Zhnn", app: 'quiver', category: "Note", label: "Copy Note Link", command: "Control-Alt-Meta-C" },
    { id: "rSJEZZkfipEDREztUozeqU", app: 'quiver', category: "Note", label: "Delete Note", command: "Meta-Delete" },
    { id: "pX64G1mTHj9eGTX89DNg95", app: 'quiver', category: "Cell", label: "New Cell", command: "Shift-Enter" },
    { id: "fhELuriprWkR9dwkWx1e4J", app: 'quiver', category: "Cell", label: "New Cell Above", command: "Meta-Shift-Enter" },
    { id: "vXyoG4DmkcRb3upLGbPX3Y", app: 'quiver', category: "Cell", label: "New Cell At Cursor", command: "Meta-Shift-I" },
    { id: "ajaFx9gNa5kPmoP1TWEq6e", app: 'quiver', category: "Cell", label: "Split Cell", command: "Alt-Meta-Enter" },
    { id: "huRoVA8RU697kAeFhqQatF", app: 'quiver', category: "Cell", label: "Cut Cell", command: "Meta-Shift-X" },
    { id: "wdb1LVdoioTkuwEKAFBAJV", app: 'quiver', category: "Cell", label: "Copy Cell", command: "Meta-Shift-C" },
    { id: "1W3dHiiUhhVggVEvP7Stb5", app: 'quiver', category: "Cell", label: "Paste Cell", command: "Meta-Shift-V" },
    { id: "rHTteeWpBs72Hkfp5kt96m", app: 'quiver', category: "Cell", label: "Delete Cell", command: "Meta-Shift-K" },
    { id: "cH1AcaT1fRF24vpkyFXWiu", app: 'quiver', category: "Cell", label: "Convert to Text Cell", command: "Alt-Meta-1" },
    { id: "nEwYQpkiePVgvrwKVBTezj", app: 'quiver', category: "Cell", label: "Convert to Code Cell", command: "Alt-Meta-2" },
    { id: "5d5BhfJHiRrcK8fXAPoeY3", app: 'quiver', category: "Cell", label: "Convert to Markdown Cell", command: "Alt-Meta-3" },
    { id: "gzd73MYEL9qeN6LkpNKKxf", app: 'quiver', category: "Cell", label: "Move Cell Up", command: "Alt-Meta-ArrowUp" },
    { id: "wgnm5hfVc23oKBkcQt6s8S", app: 'quiver', category: "Cell", label: "Move Cell Down", command: "Alt-Meta-ArrowDown" },
    { id: "vczE7251PuKWcE2ZYbw7rW", app: 'quiver', category: "Format", label: "Heading 1", command: "Control-Shift-1" },
    { id: "nhhgHXq24JdqSvmpTsRygZ", app: 'quiver', category: "Format", label: "Heading 2", command: "Control-Shift-2" },
    { id: "2fAYoB67kuKarF35JHR5Zv", app: 'quiver', category: "Format", label: "Heading 3", command: "Control-Shift-3" },
    { id: "iZn3XVHwT2iPoXuw47grHA", app: 'quiver', category: "Format", label: "Heading 4", command: "Control-Shift-4" },
    { id: "2XVZGLTjLmaKwV1KKqC7h1", app: 'quiver', category: "Format", label: "Increase Heading Level", command: "Control-Shift-]" },
    { id: "iMTSMkK1c4KXytu7UmLDwu", app: 'quiver', category: "Format", label: "Decrease Deading Level", command: "Control-Shift-[" },
    { id: "ik4NUKr3gPfbdhiNbZ5a9a", app: 'quiver', category: "Format", label: "Add/Edit Link", command: "Meta-K" },
    { id: "4MfKzsa1JP87Wj542iorxK", app: 'quiver', category: "Format", label: "Bold", command: "Meta-B" },
    { id: "bD9HPWJ2VbpXCXYB6PvpBZ", app: 'quiver', category: "Format", label: "Italic", command: "Meta-I" },
    { id: "dQYqD3HruSE4FVQEPJAYpd", app: 'quiver', category: "Format", label: "Underline", command: "Meta-U" },
    { id: "w1THVHiUahn3zxFFQBWDXk", app: 'quiver', category: "Format", label: "Strikethrough", command: "Control-Shift-S" },
    { id: "pDNDLTkP1ZNcD3phMYn5xD", app: 'quiver', category: "Format", label: "Highlight", command: "Control-Shift-H" },
    { id: "41NoqaN6hkDGPSHmfwKR7A", app: 'quiver', category: "Format", label: "Inline Code", command: "Control-Shift-K" }
];
