const quiver_shortcuts = [
    { category: "Note", label: "Toggle Editor/Preview", cmd: "cmd-shift-P" },
    { category: "Note", label: "Edit Note Tags", cmd: "cmd-'" },
    { category: "Note", label: "Copy Note Link", cmd: "ctrl-alt-cmd-C" },
    { category: "Note", label: "Delete Note", cmd: "cmd-delete" },
    { category: "Cell", label: "New Cell", cmd: "shift-return" },
    { category: "Cell", label: "New Cell Above", cmd: "cmd-shift-return" },
    { category: "Cell", label: "New Cell At Cursor", cmd: "cmd-shift-I" },
    { category: "Cell", label: "Split Cell", cmd: "alt-cmd-return" },
    { category: "Cell", label: "Cut Cell", cmd: "cmd-shift-X" },
    { category: "Cell", label: "Copy Cell", cmd: "cmd-shift-C" },
    { category: "Cell", label: "Paste Cell", cmd: "cmd-shift-V" },
    { category: "Cell", label: "Delete Cell", cmd: "cmd-shift-K" },
    { category: "Cell", label: "Convert to Text Cell", cmd: "alt-cmd-1" },
    { category: "Cell", label: "Convert to Code Cell", cmd: "alt-cmd-2" },
    { category: "Cell", label: "Convert to Markdown Cell", cmd: "alt-cmd-3" },
    { category: "Cell", label: "Move Cell Up", cmd: "alt-cmd-up" },
    { category: "Cell", label: "Move Cell Down", cmd: "alt-cmd-down" },
    { category: "Format", label: "Heading 1", cmd: "ctrl-shift-1" },
    { category: "Format", label: "Heading 2", cmd: "ctrl-shift-2" },
    { category: "Format", label: "Heading 3", cmd: "ctrl-shift-3" },
    { category: "Format", label: "Heading 4", cmd: "ctrl-shift-4" },
    { category: "Format", label: "Increase Heading Level", cmd: "ctrl-shift-]" },
    { category: "Format", label: "Decrease Deading Level", cmd: "ctrl-shift-[" },
    { category: "Format", label: "Add/Edit Link", cmd: "cmd-K" },
    { category: "Format", label: "Bold", cmd: "cmd-B" },
    { category: "Format", label: "Italic", cmd: "cmd-I" },
    { category: "Format", label: "Underline", cmd: "cmd-U" },
    { category: "Format", label: "Strikethrough", cmd: "ctrl-shift-S" },
    { category: "Format", label: "Highlight", cmd: "ctrl-shift-H" },
    { category: "Format", label: "Inline Code", cmd: "ctrl-shift-K" },
];


export default quiver_shortcuts;
